config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get 'change_locale/:locale' => 'application#change_locale', as: :change_locale
  get 'restaurants/search' => 'restaurants#search', as: :restaurant_search
  get 'restaurants/listing' => 'restaurants#listing', as: :restaurant_listing
  get 'owner/restaurants' => 'users#restaurants', as: :users_restaurant
  get 'owner/restaurants/new' => 'restaurants#owner_new', as: :owner_resto_new
  get 'owner/restaurants/:id' => 'restaurants#owner_edit', as: :owner_resto_edit
  patch 'owner/restaurants/:id' => 'restaurants#owner_patch', as: :owner_resto_patch
  get 'owner/notifications' => 'notifications#index', as: :notifications
  delete 'owner/notifications/:id' => 'notifications#destroy', as: :delete_notification
  get 'restaurants/reject/:id' => 'restaurants#reject', as: :restaurant_reject
  post 'restaurants/ratings/more/:id' => 'ratings#show_more', as: :show_more_rating
  post 'restaurants/ratings/:id' => 'ratings#more_reviews', as: :show_more_reviews
  post 'restaurants/post/more/:id' => 'posts#show_more', as: :show_more_post
  post 'restaurants/pictures/more/:id' => 'pictures#show_more', as: :show_more_picture

  get 'home/about' => 'home#about', as: :about_page
  get 'home/contact' => 'home#contact', as: :contact_page
  get 'home/index'
  get '/cuisines' => 'cuisines#index', as: :cuisines
  devise_for :users, :controllers => { :registrations => :registrations, :omniauth_callbacks => :omniauth_callbacks }
  devise_scope :user do
    delete '/admin/logout', :to => 'active_admin/devise/sessions#destroy', as: :admin_logout
  end
  resources :restaurants, except: :index
  resources :foods
  resources :pictures
  resources :ratings
  resources :schedules
  resources :users, except: :index
  resources :posts
  resources :replies

  post 'likes' => 'likes#create', as: :likes
  delete 'likes' => 'likes#destroy', as: :delete_like

  get 'users/:id' => 'users#show', as: :user_profile

  get '*path' => redirect('/')
  root 'home#index', as: 'home'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :name, :username, presence: true
  validates_length_of :name, minimum: 6
  validates :username, uniqueness: true
  validates_format_of :avatar, with: %r{\.(gif|jpg|png|jpeg)\Z}i, allow_blank: true, on: :update, if: :avatar_check?
  validates_format_of :username, without: %r{[\s-]}
  after_destroy :ensure_an_admin_remains
  mount_uploader :avatar, AvatarUploader
  has_many :restaurants, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :pictures, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :replies, dependent: :destroy
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
  
  def avatar_check?
    avatar.nil? || avatar.present? 
  end
  
  def check_notification
    if notifications.where(status: false).count > 0
      "<span class='label label-danger' style='margin-left: 10px;'>New</span>"
    end
  end
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.username = auth.info.name.split(' ').join('').downcase
      user.name = auth.info.name  # assuming the user model has a name
      user.remote_avatar_url = auth.info.image.gsub('http://','https://')
      puts "@@@@@@@####### @@@@@@@@####### #{user.name}"
      puts "@@@@@@@####### @@@@@@@@####### #{auth.info.image}"
      puts "@@@@@@@####### @@@@@@@@####### #{user.remote_avatar_url}"
    end
  end
  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
  
  private
  
  def ensure_an_admin_remains
    if User.where(admin: true).count.zero?
      raise "Can't delete last admin"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html
  layout "owner", only: [:restaurants]
  before_action :set_user, only: [:show, :edit, :update]
  before_action :authorize, only: [:edit, :update]
  before_action :authorize_owner, only: [:restaurants]
  skip_before_action :authenticate_user!, only: :show
  
  def show
  end
  
  def restaurants
    @restaurants = current_user.restaurants
    respond_with(@restaurants, template: 'users/owner/restaurants') 
  end

  def edit
    respond_with(@user, template: 'users/admin/edit')
  end
  
  def update
    @user.update(user_params)
    respond_with(@user, location: administrator_path)
  end
  
  private
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def user_params
    params.require(:user).permit(:name, :username, :email, :location, :profile_picture_url)
  end
  
  def authorize_owner
    if current_user.restaurants.blank?
      flash[:failure] = t('.noresto')
      redirect_to home_path
    end
  end
end

app/views/users/_reviews.html.erb
          <% @user.ratings.order("created_at desc").each do |rate| %>
            <div class="media">
              <div class="media-left">
                <div class="img-circle" style="width: 44px; height: 44px; background: url('<%= asset_path(display_resto(rate.restaurant))%>'); background-size: cover; background-position: center; "></div>
              </div>
              <div class="media-body">
                <h4 class="media-heading"><%= link_to rate.restaurant.name, rate.restaurant %> 
                  <small>
                    - <%= distance_of_time_in_words_to_now(rate.created_at) %> ago
                  </small>
                </h4>
                <p style="color: #bbb"><%= rate.restaurant.address %></p>

                <p><%= t('.rated')%> <span class="badge" style="margin-top: -3px; padding: 2px 4px; background-color: #CF2228;"><%= rate.rate %></span>&nbsp;&nbsp; <%= rate.comment %></p>
                  <% if user_signed_in? %>
                  <p>
                    <% if rate.user_liked?(current_user) %>
                      <%= link_to "#{t('.unlike')} #{icon('heart-o', pluralize(rate.likes.count, t('.like')))}".html_safe, delete_like_path(user: current_user.id, rating: rate.id, user_page: @user.id), class: 'btn btn-like-comment', method: :delete, remote: true %> 
                    <% else %>
                      <%= link_to "#{icon('heart-o', pluralize(rate.likes.count, t('.like')))}".html_safe, likes_path(rate_id: rate.id, user_page: @user.id), class: 'btn btn-like-comment', method: :post, remote: true %> 
                    <% end %>
                    <%= link_to "#{icon('comments-o', pluralize(rate.replies.count, t('.reply')))}".html_safe, new_reply_path(rate: rate.id, user: @user.id), class: 'btn btn-like-comment', remote: true %>
                  </p>
                <% else %>
                  <p>
                    <%= link_to "#{icon('heart-o', pluralize(rate.likes.count, t('.like')))}".html_safe, new_user_session_path, class: 'btn btn-like-comment', method: :post, remote: true, disabled: true, data: { toggle: 'tooltip', placement: 'top', title: t('.signintolike')} %> 
                    <%= link_to "#{icon('comments-o', pluralize(rate.replies.count, t('.reply')))}".html_safe, new_user_session_path, class: 'btn btn-like-comment', remote: true, disabled: true, data: { toggle: 'tooltip', placement: 'top', title: t('.signintoreply')} %>
                  </p>
                <% end %>
              </div>
            </div>
            <div class="media" style="padding: 0px 50px; margin: 0px;">
              <% if rate.replies.count > 3 %>
                <% if @all == "true" && @review_id.to_i == rate.id %>
                <%= link_to "#{t('.viewless')} #{icon('caret-up')}".html_safe, show_more_rating_path(@user, rate_id: rate.id, more: false, user: true), class: 'center-block text-center', style: 'width: 100%; background-color: whitesmoke; padding: 3px; color: #777777;', remote: true, method: :post %>
                <% else %>
                  <%= link_to "#{t('.viewall')} (#{rate.replies.count - 3}) #{icon('caret-down')}".html_safe, show_more_rating_path(@user, rate_id: rate.id, more: true, user: true), class: 'center-block text-center', style: 'width: 100%; background-color: whitesmoke; padding: 3px; color: #777777;', remote: true, method: :post %>
                <% end %>
              <% end %>
            </div>
            <% if rate.replies.present? %>
              <% (@all == "true" && @review_id.to_i == rate.id ? rate.replies : rate.replies.last(3)).each do |reply| %>
                <div class="media" style="padding: 10px 50px 10px 50px; margin: 0px;">
                  <div class="media-left">
                    <div style="background: url('<%= asset_path(display_user(reply.user)) %>'); background-size: cover; background-position: center center; width: 40px; height: 40px;" class="img-circle"></div>
                  </div>
                  <div class="media-body" style="max-width: 565px;">
                    <h5 class="media-heading">
                      <%= reply.user.name %> <small> - <%= distance_of_time_in_words_to_now(reply.created_at) %> ago</small>
                      <% if reply.user === current_user %>
                        <span style="margin-left: 20px;">
                          <%= link_to "#{icon('trash')}".html_safe, reply_path(reply, rate: true, user: @user), method: :delete, remote: true %>
                        </span>
                      <% end %>
                    </h5>
                    <p><%= reply.comment %></p>
                  </div>
                </div>
              <% end %>
            <% end %>
            <div id="rating_reply_<%= rate.id %>" style="padding: 5px 20px;">

            </div>
          <% end %>

app/views/users/show.html.erb
<div class="container" style="max-width: 750px;">
  <div class="row" style="margin-top: 30px; background-color: #fff; padding: 20px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.1), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
    <div class="col-md-3">
      <div class="img-responsive img-circle center-block" style="background: url('<%= asset_path(display_user(@user))%>'); width: 140px; height: 140px; border: 5px solid white; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19); background-size: cover; background-position: center;">
      </div>
    </div>
    <div class="col-md-9">
      <h3><%= @user.name %> <small> @<%= @user.username %></small></h3>
      <p><%= icon('envelope', @user.email) %></p>
      <% if @user === current_user %>
        <p><%= link_to "#{icon('pencil-square-o')} #{t('.editprofile')}".html_safe, edit_user_registration_path %></p>
      <% end %>
    </div>
  </div>
  
  <div class="row" style="margin-top: 20px; background-color: #fff; padding: 20px; margin-bottom: 60px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.1), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
    <ul id="user-tabs" class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active"><a data-target="#fudline" aria-controls="fudline" role="tab" data-toggle="tab">Fudline</a></li>
      <li role="presentation" class=""><a data-target="#reviewed" aria-controls="reviewed" role="tab" data-toggle="tab"><%= t('.reviewedresto')%></a></li>
      <li role="presentation" class=""><a data-target="#photos" aria-controls="photos" role="tab" data-toggle="tab"><%= t('.uploadedphotos')%></a></li>
    </ul>
    
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane fade in active" id="fudline" style="padding: 20px;">
        <% unless @user.ratings.empty? %>
          <div id="user_reviews_area">
            <%= render 'users/reviews'%>
          </div>
        <% end %>
        <div class="media">
          <div class="media-left">
            <div class="img-circle" style="width: 44px; height: 44px; background: url('<%= asset_path(display_user(@user))%>'); background-size: cover; background-position: center; "></div>
          </div>
          <div class="media-body">
            <h4 class="media-heading"><%= @user.name %></h4>
            <p><%= t('.startfudz')%></p>
            <p><%= distance_of_time_in_words_to_now(@user.created_at) %> ago</p>
          </div>
        </div>
      </div>
      <div role="tabpanel" class="tab-pane fade in" id="reviewed" style="padding: 20px;">
        <% if @user.ratings.present? %>
          <div class="row">
            <% @user.ratings.each do |rating| %>  
              <%= link_to rating.restaurant do %>
                <div class="module col-md-4 col-sm-6 col-xs-12 hvr-grow" style="background: linear-gradient( to bottom, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.4)), url('<%= asset_path(display_resto(rating.restaurant))  %>');background-repeat: no-repeat; background-position: center center; background-size: cover; border: 4px solid #fff; border-radius: 20px;">
                  <header>
                    <h3>
                      <%= rating.restaurant.name %><br>
                      <small style="color: #fff;">
                        <% (rating.restaurant.ave_ratings.to_i).times do %>
                          <%= icon('star') %>
                        <% end %>
                        <% unless rating.restaurant.ave_ratings % 1 == 0 %>
                          <%= icon('star-half-o')%>
                          <% (4 - rating.restaurant.ave_ratings.to_i).times do %>
                            <%= icon('star-o') %>
                          <% end %>
                        <% else %>
                          <% (5 - rating.restaurant.ave_ratings.to_i).times do %>
                            <%= icon('star-o') %>
                          <% end %>
                        <% end %>
                      </small>
                    </h3>
                  </header>
                </div>
              <% end %>
            <% end %>
          </div>
        <% else %>
          <p style="margin-left: -5px;"><%= t('.noreviews')%></p>
        <% end %>
        
      </div>
      <div role="tabpanel" class="tab-pane fade in" id="photos" style="padding: 20px;">
        <div class="row pic-row" style = 'padding-left: 20px;'>
          <% unless @user.pictures.empty? %>
            <% @user.pictures.where(status: true).each do |picture| %>
              <%= link_to picture_path(picture), remote: true, data: { toggle: 'modal', target: '#myModal' } do %>
                <div class="col-md-3 col-sm-4 col-xs-6 img-responsive" style = 'background-image: url(<%= picture.pic.url %>); background-repeat: no-repeat; background-size: cover; background-position: center; border: 4px solid #fff; border-radius: 15px;'>
                </div>
              <% end %>
            <% end %>
          <% else %>
            <p style="margin-left: -5px;"><%= t('.nophotos')%></p>
          <% end %>
        </div>
      </div>
    </div>
    
  </div>
</div>

    
    
    
    
    
<div class="modal fade" id="edit_user_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-md" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= t('.edituserinfo')%></h4>
      </div>
      <div class="modal-body">
        <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
          <%= devise_error_messages! %>

          <div class="form-group">
            <%= f.label :email, t('.email') %><br />
            <%= f.email_field :email, autofocus: true, class: 'form-control'%>
          </div>

          <div class="form-group">
            <%= f.label :username, t('.username') %><br />
            <%= f.text_field :username , class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :name, t('.name') %><br />
            <%= f.text_field :name , class: 'form-control' %>
          </div>

          <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
            <div><%= t('.pendingconfirm', email: resource.unconfirmed_email) %></div>
          <% end %>

          <div class="form-group">
            <%= f.label :avatar, t('.avatar') %><br />
            <%= f.file_field :avatar %>
          </div>

          <div class="form-group">
            <%= f.label :location, t('.location') %><br />
            <%= f.text_field :location, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password, t('.password') %> <i><%= t('.passwordinfo')%></i><br />
            <%= f.password_field :password, autocomplete: "off" %>
          </div>

          <div class="field">
            <%= f.label :password_confirmation, t('.passwordconfirmation') %><br />
            <%= f.password_field :password_confirmation, autocomplete: "off" %>
          </div>

          <div class="field">
            <%= f.label :current_password, t('.currentpassword') %> <i><%= t('.currentpasswordinfo')%></i><br />
            <%= f.password_field :current_password, autocomplete: "off" %>
          </div>

          <div class="actions">
            <%= f.submit t('.submitupdate') %>
          </div>
        <% end %>

        <h3><%= t('.cancel')%></h3>

        <p><%= t('.unhappy')%> <%= button_to t('.cancel'), registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %></p>
      </div>
    </div>
  </div>
</div>