config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get 'change_locale/:locale' => 'application#change_locale', as: :change_locale
  get 'restaurants/search' => 'restaurants#search', as: :restaurant_search
  get 'restaurants/listing' => 'restaurants#listing', as: :restaurant_listing
  get 'owner/restaurants' => 'users#restaurants', as: :users_restaurant
  get 'owner/restaurants/new' => 'restaurants#owner_new', as: :owner_resto_new
  get 'owner/restaurants/:id' => 'restaurants#owner_edit', as: :owner_resto_edit
  patch 'owner/restaurants/:id' => 'restaurants#owner_patch', as: :owner_resto_patch
  get 'owner/notifications' => 'notifications#index', as: :notifications
  delete 'owner/notifications/:id' => 'notifications#destroy', as: :delete_notification
  get 'restaurants/reject/:id' => 'restaurants#reject', as: :restaurant_reject
  post 'restaurants/ratings/more/:id' => 'ratings#show_more', as: :show_more_rating
  post 'restaurants/ratings/:id' => 'ratings#more_reviews', as: :show_more_reviews
  post 'restaurants/post/more/:id' => 'posts#show_more', as: :show_more_post
  post 'restaurants/pictures/more/:id' => 'pictures#show_more', as: :show_more_picture

  get 'home/about' => 'home#about', as: :about_page
  get 'home/contact' => 'home#contact', as: :contact_page
  get 'home/index'
  get '/cuisines' => 'cuisines#index', as: :cuisines
  devise_for :users, :controllers => { :registrations => :registrations, :omniauth_callbacks => :omniauth_callbacks }
  devise_scope :user do
    delete '/admin/logout', :to => 'active_admin/devise/sessions#destroy', as: :admin_logout
  end
  resources :restaurants, except: :index
  resources :foods
  resources :pictures
  resources :ratings
  resources :schedules
  resources :users, except: :index
  resources :posts
  resources :replies

  post 'likes' => 'likes#create', as: :likes
  delete 'likes' => 'likes#destroy', as: :delete_like

  get 'users/:id' => 'users#show', as: :user_profile

  get '*path' => redirect('/')
  root 'home#index', as: 'home'
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :user
  has_many :likes
  has_many :replies
  
  validates :rate, :user, :restaurant, presence: true
  
  def user_liked?(user)
    likes.where(user: user).present?
  end
  
  def self.sort(sort_value, order)  
      if sort_value == 'Rating'
        @ratings = Rating.order("rate #{order[0]}")
        order[0] == 'ASC' ? order[0] = 'DESC' : order[0] = 'ASC'
      elsif sort_value == 'Restaurant'
        @ratings = Rating.joins("LEFT JOIN restaurants on ratings.restaurant_id = restaurants.id").order("LOWER(name) #{order[1]}")
        order[1] == 'ASC' ? order[1] = 'DESC' : order[1] = 'ASC'
      elsif sort_value == 'User'
        @ratings = Rating.joins("LEFT JOIN users on ratings.user_id = users.id").order("LOWER(name) #{order[2]}")
        order[2] == 'ASC' ? order[2] = 'DESC' : order[2] = 'ASC'
      else
        @ratings = Rating.order('updated_at DESC')
      end
      return @ratings, order
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  
  respond_to :html
  respond_to :js, only: [:edit, :show_more, :more_reviews]
  before_action :set_rating, only: [:edit, :update]
  before_action :authorize, only: [:index]
  skip_before_action :authenticate_user!, only: :show_more
  
  def index
    
  end
  
  def show_more
    @all = params[:more] || nil
    @review_id = params[:rate_id]
    @more_reviews = params[:review]
    puts "############ #{@all}"
    @restaurant = Restaurant.find(params[:id]) unless params[:user].present?
    @user = User.find(params[:id]) if params[:user].present?
    respond_with(@all)
  end
  
  def more_reviews
    @more_reviews = params[:more]
    @restaurant = Restaurant.find(params[:id]) unless params[:user].present?
    respond_with(@all)
  end
  
  def create
    @rating = Rating.new(rate_params)
    @rating.user = current_user
    if @rating.save 
      flash[:success] = t('.success')
      Notification.create(message: "#{view_context.link_to current_user.name, user_path(current_user)} rated on your restaurant #{view_context.link_to @rating.restaurant.name, restaurant_path(@rating.restaurant)} with a #{@rating.rate} star rating.", user: @rating.restaurant.user)
      respond_with(@rating, location: @rating.restaurant)
    else
      flash[:failure] = "<dl><dt>#{t('.failurestart')}</dt>" 
      @rating.errors.full_messages.map { |msg| flash[:failure] << "<dd>#{msg}</dd>" }
      flash[:failure] << "</dl>"
      redirect_to restaurant_path(@rating.restaurant)
    end
  end
  
  def update
    if @rating.update(rate_params)
      flash[:success] = t('.success')
      respond_with(@rating, location: restaurant_path(@rating.restaurant))
    else
      flash[:failure] = "<dl><dt>#{t('.failurestart')}</dt>" 
      @rating.errors.full_messages.map { |msg| flash[:failure] << "<dd>#{msg}</dd>" }
      flash[:failure] << "</dl>"
      redirect_to restaurant_path(@rating.restaurant)
    end
  end
  
  def edit
  end
  
  private
  
  def rate_params
    params.require(:rating).permit(:rate, :comment, :restaurant_id)
  end
  
  def set_rating
    @rating = Rating.find(params[:id])
  end
end

app/views/ratings/_edit.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <h4 class="modal-title" id="myModalLabel"><%= t('.editreview')%></h4>
</div>
<div class="modal-body">
  <%= form_for(@rating, url: rating_path(@rating.id), method: :put) do |f| %>
    <div class="">
        <fieldset class="rating">
          <%= f.radio_button :rate, 5, id: 'star5edit' %>
          <%= label_tag :star5edit, "", class: 'full', title: '5 Stars' %>
          <%= f.radio_button :rate, 4, id: 'star4edit'  %>
          <%= label_tag :star4edit, "", class: 'full', title: '4 Stars' %>
          <%= f.radio_button :rate, 3, id: 'star3edit'  %>
          <%= label_tag :star3edit, "", class: 'full', title: '3 Stars' %>
          <%= f.radio_button :rate, 2, id: 'star2edit'  %>
          <%= label_tag :star2edit, "", class: 'full', title: '2 Stars' %>
          <%= f.radio_button :rate, 1, id: 'star1edit'  %>
          <%= label_tag :star1edit, "", class: 'full', title: '1 Star' %>
        </fieldset>
    </div>
    <div class="form-group">
      <%= f.text_area :comment, class: 'form-control', placeholder: t('.comment')%>
    </div>
  
    <div class="actions">
      <%= f.submit t('.editreview'), class: 'btn btn-primary', style: 'width: 100%;' %>
    </div>
  
  <% end %>
</div>

app/views/ratings/_rating.html.erb
<% unless @restaurant.ratings.empty? %>
  <% (@more_reviews == 'true' ? @restaurant.ratings.order(created_at: :desc) : @restaurant.ratings.order(created_at: :desc).limit(5)).each do |rate| %>
    <div class="media">
      <div class="media-left">
        <div class="img-circle" style="width: 44px; height: 44px; background: url('<%= asset_path(display_user(rate.user))%>'); background-size: cover; background-position: center; "></div>
      </div>
      <div class="media-body" style="max-width: 575px;">
        <h4 class="media-heading">
          <%= link_to rate.user.name, rate.user %> 
          <small>
            - <%= distance_of_time_in_words_to_now(rate.created_at) %> ago
            <% if current_user === rate.user %> 
              <%= link_to "#{icon('pencil', nil, style: 'margin-left: 20px;')}".html_safe, edit_rating_path(rate), remote: true, data: { toggle: 'modal', target: '#myModal'} %>
            <% end %>
          </small>  
        </h4>
        <p style="color: #bbb;"><small><%= pluralize(rate.user.ratings.count, "Review") %></small></p>
        <p><%= t('.rated')%> <span class="badge" style="margin-top: -3px; padding: 2px 4px; background-color: #CF2228;"><%= rate.rate %></span>&nbsp;&nbsp; <%= rate.comment %></p>
        <% if user_signed_in? %>
          <p>
            <% if rate.user_liked?(current_user) %>
              <%= link_to "#{t('.unlike')} #{icon('heart-o', pluralize(rate.likes.count, t('.like')))}".html_safe, delete_like_path(user: current_user.id, rating: rate.id, review: @more_reviews), class: 'btn btn-like-comment', method: :delete, remote: true %> 
            <% else %>
              <%= link_to "#{icon('heart-o', pluralize(rate.likes.count, t('.like')))}".html_safe, likes_path(rate_id: rate.id, review: @more_reviews), class: 'btn btn-like-comment', method: :post, remote: true %> 
            <% end %>
            <%= link_to "#{icon('comments-o', pluralize(rate.replies.count, t('.reply')))}".html_safe, new_reply_path(rate: rate.id, review: @more_reviews), class: 'btn btn-like-comment', remote: true %>
          </p>
        <% else %>
          <p>
            <%= link_to "#{icon('heart-o', pluralize(rate.likes.count, t('.like')))}".html_safe, new_user_session_path, class: 'btn btn-like-comment', method: :post, remote: true, disabled: true, data: { toggle: 'tooltip', placement: 'top', title: t('.signintolike')} %> 
            <%= link_to "#{icon('comments-o', pluralize(rate.replies.count, t('.reply')))}".html_safe, new_user_session_path, class: 'btn btn-like-comment', remote: true, disabled: true, data: { toggle: 'tooltip', placement: 'top', title: t('.signintoreply')} %>
          </p>
        <% end %>
      </div>
    </div>
    <div class="media" style="padding: 0px 50px; margin: 0px;">
      <% puts "@@@@@@@@@@ #{@review_id.class}"%>
      <% if rate.replies.count > 3 %>
        <% if @all == "true" && @review_id.to_i == rate.id %>
          <%= link_to "#{t('.viewless')} #{icon('caret-up')}".html_safe, show_more_rating_path(@restaurant, rate_id: rate.id, more: false, review: @more_reviews), class: 'center-block text-center', style: 'width: 100%; background-color: whitesmoke; padding: 3px; color: #777777;', remote: true, method: :post %>
        <% else %>
          <%= link_to "#{t('.viewall')} (#{rate.replies.count - 3}) #{icon('caret-down')}".html_safe, show_more_rating_path(@restaurant, rate_id: rate.id, more: true, review: @more_reviews), class: 'center-block text-center', style: 'width: 100%; background-color: whitesmoke; padding: 3px; color: #777777;', remote: true, method: :post %>
        <% end %>
      <% end %>
    </div>
    <% if rate.replies.present? %>
      <% (@all == "true" && @review_id.to_i == rate.id ? rate.replies : rate.replies.last(3)).each do |reply| %>
        <div class="media" style="padding: 10px 50px 10px 53px; margin: 0px;">
          <div class="media-left">
            <div style="background: url('<%= asset_path(display_user(reply.user)) %>'); background-size: cover; background-position: center center; width: 40px; height: 40px;" class="img-circle"></div>
          </div>
          <div class="media-body" style="max-width: 565px;">
            <h5 class="media-heading">
              <%= reply.user.name %> <small> - <%= distance_of_time_in_words_to_now(reply.created_at) %> ago</small>
              <% if reply.user === current_user %>
                <span style="margin-left: 20px;">
                  <%= link_to "#{icon('trash')}".html_safe, reply_path(reply, rate: true), method: :delete, remote: true %>
                </span>
              <% end %>
            </h5>
            <p><%= reply.comment %></p>
          </div>
        </div>
      <% end %>
    <% end %>
    <div id="rating_reply_<%= rate.id %>" style="padding: 5px 20px;">
          
    </div>
  <% end %>
  <% if @restaurant.ratings.count > 5 %>
    <% if @more_reviews == "true" %>
<%= link_to t('.viewless'), show_more_reviews_path(@restaurant, more: false), class: 'center-block text-center', style: 'width: 100%; background-color: whitesmoke; padding: 10px; color: #777777;', remote: true, method: :post %>
    <% else %>
<%= link_to "#{t('.viewall')} (#{5 - @restaurant.ratings.count})", show_more_reviews_path(@restaurant, more: true), class: 'center-block text-center', style: 'width: 100%; background-color: whitesmoke; padding: 10px; color: #777777;', remote: true, method: :post %>
    <% end %>
  <% end %>
<% else %>
  <div style="height: 75px;">
    <h4><%= t('.noreviews')%></h4>
  </div>
<% end %>

app/views/ratings/edit.js.erb
$("#show-modal").html('<%= j render "edit" %>')

app/views/ratings/index.html.erb
<table class = 'table'>
	<th><%= link_to t('.rating'), ratings_path(:search_category => "Rating", :search_order => @order) %></th>
	<th><%= link_to t('.restaurant'), ratings_path(:search_category => "Restaurant", :search_order => @order) %></th>
	<th><%= link_to t('.user'), ratings_path(:search_category => "User", :search_order => @order) %></th>
	<th><%= t('.comment') %></th>
	
<% @ratings.each do |rating| %>
	<tr>
		<td><%= rating.rate %></td>
		<td><%= rating.restaurant.try(:name) %></td>
		<td><%= rating.user.name %></td>
		<td><%= rating.comment %></td>
	</tr>
<% end%>
</table>

app/views/ratings/more_reviews.js.erb
$('#reviews_area').html("<%= j render('ratings/rating', all: @all, restaurant: @restaurant)%>")

app/views/ratings/show_more.js.erb
<% if @restaurant.present? %>
  $('#reviews_area').html("<%= j render('ratings/rating', all: @all, restaurant: @restaurant, review_id: @review_id)%>")
<% else %>
  $('#user_reviews_area').html("<%= j render('users/reviews', all: @all, user: @user) %>")
<% end %>