config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get 'change_locale/:locale' => 'application#change_locale', as: :change_locale
  get 'restaurants/search' => 'restaurants#search', as: :restaurant_search
  get 'restaurants/listing' => 'restaurants#listing', as: :restaurant_listing
  get 'owner/restaurants' => 'users#restaurants', as: :users_restaurant
  get 'owner/restaurants/new' => 'restaurants#owner_new', as: :owner_resto_new
  get 'owner/restaurants/:id' => 'restaurants#owner_edit', as: :owner_resto_edit
  patch 'owner/restaurants/:id' => 'restaurants#owner_patch', as: :owner_resto_patch
  get 'owner/notifications' => 'notifications#index', as: :notifications
  delete 'owner/notifications/:id' => 'notifications#destroy', as: :delete_notification
  get 'restaurants/reject/:id' => 'restaurants#reject', as: :restaurant_reject
  post 'restaurants/ratings/more/:id' => 'ratings#show_more', as: :show_more_rating
  post 'restaurants/ratings/:id' => 'ratings#more_reviews', as: :show_more_reviews
  post 'restaurants/post/more/:id' => 'posts#show_more', as: :show_more_post
  post 'restaurants/pictures/more/:id' => 'pictures#show_more', as: :show_more_picture

  get 'home/about' => 'home#about', as: :about_page
  get 'home/contact' => 'home#contact', as: :contact_page
  get 'home/index'
  get '/cuisines' => 'cuisines#index', as: :cuisines
  devise_for :users, :controllers => { :registrations => :registrations, :omniauth_callbacks => :omniauth_callbacks }
  devise_scope :user do
    delete '/admin/logout', :to => 'active_admin/devise/sessions#destroy', as: :admin_logout
  end
  resources :restaurants, except: :index
  resources :foods
  resources :pictures
  resources :ratings
  resources :schedules
  resources :users, except: :index
  resources :posts
  resources :replies

  post 'likes' => 'likes#create', as: :likes
  delete 'likes' => 'likes#destroy', as: :delete_like

  get 'users/:id' => 'users#show', as: :user_profile

  get '*path' => redirect('/')
  root 'home#index', as: 'home'
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  
  include FindByOrderedIds
  
  mount_uploader :avatar, AvatarUploader
  mount_uploader :cover, AvatarUploader
  include ActionView::Helpers::SanitizeHelper
  belongs_to :user
  
  has_many :ratings, dependent: :destroy
  has_many :foods, dependent: :destroy
  has_many :pictures, dependent: :destroy
  has_many :schedules, dependent: :destroy
  has_many :cuisines, through: :foods
  has_many :posts, dependent: :destroy
  has_one :location, dependent: :destroy
  
  validates :name, :contact, :user, presence: true
  validates_format_of :avatar, with: %r{\.(gif|jpg|png|jpeg)\Z}i, allow_blank: true, on: :update, if: :avatar_check?
  validates_format_of :cover, with: %r{\.(gif|jpg|png|jpeg)\Z}i, allow_blank: true, on: :update, if: :cover_check?
  validates_format_of :website, with: %r{\A(http|https|ftp|ftps):\/\/(([a-z0-9]+\:)?[a-z0-9]+\@)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?\Z}ix,
                                allow_blank: true  
                                
  validates_format_of :contact, with: %r{\A[\d\-\+]*\Z}
                                  
  def avatar_check?
    avatar.nil? || avatar.present?
  end

  def cover_check?
    cover.nil? || cover.present?
  end
  
  def cuisine_list
    Cuisine.where(id: self.foods.map(&:cuisine_id).uniq)
  end
  
  def ave_ratings
    unless ratings.empty?
      ratings.collect(&:rate).sum.to_f/ratings.size 
    else
      0
    end
  end
  
  def is_open?(current)
    scheds = schedules.group_by{|s| [s.day]}
    @hours = ""

    mappings = {["Sunday"] => 0, ["Monday"] => 1, ["Tuesday"] => 2, ["Wednesday"] => 3, ["Thursday"] => 4, ["Friday"] => 5, ["Saturday"] => 6}
    scheds = scheds.map {|k, v| [mappings[k], v] }.to_h

    scheds = scheds.sort_by{ |k,v| k }.to_h

    today_time = current.to_time.to_a
    scheds.each do |key, value|
      if current.wday == key
        value.each do |val|
          open_time = Time.parse(val.opening).to_a
          close_time = Time.parse(val.closing).to_a

          close_time[2] = close_time[2] + 24 if Time.at(Time.parse(val.opening).to_i) > (Time.at(Time.parse(val.closing).to_i))

          if (open_time[2]..close_time[2]).cover? today_time[2]
            if today_time[2] == close_time[2]
              return true if ((0..close_time[1]).cover? today_time[1])
            elsif today_time[2] == open_time[2]
              return true if ((open_time[1]..59).cover? today_time[1])
            else
              return true
            end
          end
        end
      end
    end
    return false
  end
  
  def sched
    scheds = schedules.group_by{|s| [s.day]}
    @hours = ""

    mappings = {["Sunday"] => 0, ["Monday"] => 1, ["Tuesday"] => 2, ["Wednesday"] => 3, ["Thursday"] => 4, ["Friday"] => 5, ["Saturday"] => 6}
    scheds = scheds.map {|k, v| [mappings[k], v] }.to_h
    scheds = scheds.sort_by{ |k,v| k }.to_h
    scheds.each do |key, value|
      @hours << "#{Date::DAYNAMES[key]} "
      value.each_with_index do |val, index|
        if value.count > 1 && index < value.count-1
          @hours << "#{val.opening} - #{val.closing}, "
        else
          @hours << "#{val.opening} - #{val.closing} "
        end
      end
    end
        
    return scheds
  end
  
  def min_price
    foods.minimum(:price).to_i
  end
  
  def max_price
    foods.maximum(:price).to_i
  end
  
  def self.search_by_name(query)
    Restaurant.where("name LIKE ?","%#{query}%").map(&:id)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :reject]
  before_action :set_pending_restaurant, only: [:destroy, :update]
  before_action :set_owner_restaurant, only: [:owner_edit, :owner_patch]
  skip_before_action :authenticate_user!, only: [:show, :search]
  layout 'owner', only: [:owner_edit, :owner_new]
  before_action :authorize, only: [:listing, :reject, :edit]
  respond_to :html

  

  def search
    @search_result = []
    @main_active = false
    sort_type = params[:sort]
    sort_type ||= 'ratings'
    if params[:cuisine].blank?
      @search_result << Cuisine.search_by_name(params[:searchQuery])
      @search_result << Restaurant.search_by_name(params[:searchQuery])    
      @search_result << Food.search_by_name(params[:searchQuery])
    else
      @search_result << Cuisine.find(params[:cuisine]).foods.where("name LIKE ?", "%#{params[:searchQuery]}%").map {|food| food.restaurant.id }
    end 
    @search_result.flatten!(1)
    
    unless params[:price_range].nil?
      @search_range = params[:price_range].split(',')
      @result = Restaurant.find(@search_result).map {|restaurant| restaurant.foods.map {|food| food.restaurant if food.price.between?(@search_range[0].to_i,@search_range[1].to_i)} }.flatten(1).compact
      @search_result = Restaurant.find(@result)
    end
    
    puts "@@@@@@@@ #{@search_result}"
    
    if params[:location].present?
      if sort_type == 'ratings'
        @result = Restaurant.where(id: Location.find(params[:location]).nearbys(3).map(&:restaurant_id) & @search_result.map(&:id), status: 'Accepted').joins("LEFT JOIN ratings ON ratings.restaurant_id = restaurants.id").group("restaurants.id").order("AVG(ratings.rate) DESC")
        puts "@@@@ DUMAAN DITO GUYS"
        puts "@@@@ #{@search_result}"
      elsif sort_type == 'name'
        @result = Restaurant.where(id: Location.find(params[:location]).nearbys(3).map(&:restaurant_id) & @search_result.map(&:id), status: 'Accepted').order('name')
      elsif sort_type == 'price_low_to_high'
        @result = Restaurant.where(id: Location.find(params[:location]).nearbys(3).map(&:restaurant_id) & @search_result.map(&:id), status: 'Accepted').includes(:foods).order('foods.price')
      else
        @result = Restaurant.where(id: Location.find(params[:location]).nearbys(3).map(&:restaurant_id) & @search_result.map(&:id), status: 'Accepted').includes(:foods).order('foods.price desc')
      end
    else
      if sort_type == 'ratings'
        @result = Restaurant.where(id: @search_result, status: 'Accepted').joins("LEFT JOIN ratings ON ratings.restaurant_id = restaurants.id").group("restaurants.id").order("AVG(ratings.rate) DESC")
      elsif sort_type == 'name'
        @result = Restaurant.order('name').where(id: @search_result, status: 'Accepted')
      elsif sort_type == 'price_low_to_high'
        @result = Restaurant.includes(:foods).order('foods.price').where(id: @search_result, status: 'Accepted')
      else
        @result = Restaurant.includes(:foods).order('foods.price desc').where(id: @search_result, status: 'Accepted')
      end
    end
    
    
    @searchQuery = params[:searchQuery] || ""
    @price_range = params[:price_range] unless params[:price_range].nil?
    @location = Location.find(params[:location]).id if params[:location].present?
    @cuisine = Cuisine.find(params[:cuisine]).id if params[:cuisine].present?
    @main_active = true if sort_type == 'ratings'
    
    unless @result.kind_of?(Array)
      @result = @result.page(params[:page])
    else
      @result = Kaminari.paginate_array(@result).page(params[:page])
    end
#    @result = @result.page(params[:page])
    respond_with(@result)
  end

  def show
    if @restaurant.blank?
      render template: 'errors/404', :layout => false, status: 404
    else
      @picture = Picture.new
      @rating = Rating.new
    end
  end

  def owner_new
    @restaurant = Restaurant.new
    respond_with(@restaurant, template: 'users/owner/new')
  end
  
  def owner_edit
    @foods = @restaurant.foods.order(created_at: :desc)
    @ratings = @restaurant.ratings(created_at: :desc)
    @schedules = @restaurant.schedules
    @posts = @restaurant.posts(created_at: :desc)
    @pictures = @restaurant.pictures.order('created_at desc')
    @picture = Picture.new
    respond_with(@restaurant, template: 'users/owner/edit')
  end
  
  def edit
  end
  
  def listing
    @restos_accepted = Restaurant.where(status: "Accepted").order('updated_at DESC')
    @restos_rejected = Restaurant.where(status: "Rejected").order('updated_at DESC')
    @restos_pending = Restaurant.where(status: "Pending").order('updated_at DESC')
  end
  
  def new
    @restaurant = Restaurant.new
    respond_with(@restaurant)
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user = current_user
    name = @restaurant.name
    
    if @restaurant.save
      if params[:latitude].present? 
        Location.create(latitude: params[:latitude], longitude: params[:longitude], restaurant: @restaurant)
        if @restaurant.address.blank?
          @restaurant.update(address: @restaurant.location.address)
        end
      end
      flash[:success] = t('.success')
      respond_with(@restaurant, location: users_restaurant_path)
    else
      flash[:failure] = "<dl><dt>#{t('.failurestart')}</dt>" 
      @restaurant.errors.full_messages.map { |msg| flash[:failure] << "<dd>#{msg}</dd>" }
      flash[:failure] << "</dl>"
      respond_with(@restaurant, location: owner_resto_new_path)
    end
  end
  
  def reject
  end
  
  def update    
#    raise
    if @restaurant.update(restaurant_params)
      if @restaurant.location.present?
        if params[:latitude].present?
          old_address = @restaurant.location.address
          @restaurant.location.update(latitude: params[:latitude], longitude: params[:longitude])
          if @restaurant.address == old_address || @restaurant.address.blank?
            @restaurant.update(address: @restaurant.location.address)
          end
        end
      else
        if params[:latitude].present?
          puts "@@@@@@@@@ #{params[:latitude]}"
          location = Location.create(latitude: params[:latitude], longitude: params[:longitude], restaurant_id: @restaurant.id)
        end
      end
      flash[:success] = t('.success')
      respond_with(@restaurant, location: owner_resto_edit_path(@restaurant))
    else
      flash[:failure] = "<dl><dt>#{t('.failurestart')}</dt>"
      @restaurant.errors.full_messages.map { |msg| flash[:failure] << "<dd>#{msg}</dd>" }
      flash[:failure] << "</dl>"
      redirect_to owner_resto_edit_path(@restaurant)
    end
  end
  
  def destroy
    name = @restaurant.name
    if @restaurant.destroy
      flash[:success] = t('.success')
      respond_with(@restaurant, location: users_restaurant_path)
    else
      flash[:failure] = "<dl><dt>#{t('.failurestart')}</dt>" 
      @restaurant.errors.full_messages.map { |msg| flash[:failure] << "<dd>#{msg}</dd>" }
      flash[:failure] << "</dl>"
      redirect_to owner_resto_edit_path(@restaurant) 
    end
  end
  
  private
  
  def restaurant_params
    params.require(:restaurant).permit(:name, :map, :address, 
      :contact, :website, :status, :cover, :avatar)
  end
    
  def set_owner_restaurant
    @restaurant = current_user.restaurants.find(params[:id])
  end
  
  
  def set_pending_restaurant
    @restaurant = Restaurant.find_by_id(params[:id])
  end

  def set_restaurant
    @restaurant = Restaurant.where(status: 'Accepted').find_by_id(params[:id])
  end
  
  def set_owner_restaurant
    @restaurant = current_user.restaurants.find(params[:id])
  end
  
end

app/views/restaurants/_searchbar.html.erb
<div class="container search_container" style="margin-top: 20px;">
  <div style='text-align: center;'>
      <%= form_tag(restaurant_search_path, method: :get, id: 'search_form') do %>
        <div class="input-group">
          <%= text_field_tag :searchQuery, (@searchQuery.blank? ? nil : @searchQuery), class: "form-control search_field", placeholder: t('.placesearch'), id: 'search_field', required: true, style: 'height: 40px;' %>
          <span class="input-group-btn">
            <%= submit_tag t('.search'), class: "btn btn-default", style: 'height: 40px; background-color: #CF2228; color: #fff; border: 1px solid #CF2228;'%>
          </span>
        </div>
      <% end %>
        <div class="row search" style="margin-top: 10px;">
          <div class="col-md-12">
            <div class="dropdown">
              <%= link_to "#{t('.searchtools')}#{icon('caret-down', style: 'margin-left: 10px;')}".html_safe, nil, class: 'dropdown-toggle', data: { toggle: 'dropdown'}, style: 'color: #000;' %>
              <ul class="dropdown-menu" style="width: 100%; color: #000; text-shadow: none;">
                <% unless Food.all.empty? %>
                  <%= form_tag(restaurant_search_path, method: :get, style: 'padding: 20px;', id: 'filter_search_form') do %>
                    <div class="form-group">
                      <%= select_tag :location, options_from_collection_for_select(Location.where(restaurant_id: nil),"id","address", @location), prompt: t('.selectplace'), class: 'form-control' %>
                    </div>
                    <div class="form-group">
                      <%= select_tag :cuisine, options_from_collection_for_select(Cuisine.all,"id","name", @cuisine), prompt: t('.selectcuisine'), class: 'form-control' %>
                    </div>
                    <%= t('.filterprice')%>
                    <div class="row">
                      <div class="col-md-3 col-sm-3 col-xs-3">
                        <b><%= t('.currency')%> <%= Food.min %></b> 
                      </div>
                      <div class="col-md-6 col-sm-6 col-xs-6">
                        <input id="price_slider" name= "price_range" type="text" class="span2" value="" data-slider-min="<%= Food.min %>" data-slider-max="<%= Food.max %>" data-slider-step="5" data-slider-value="[<%= "#{@search_range[0].to_i if @search_range.present?}#{Food.min unless @search_range.present?}" %>,<%= "#{@search_range[1].to_i if @search_range.present?}#{Food.max unless @search_range.present?}"%>]"/> 
                      </div>
                      <div class="col-md-3 col-sm-3 col-xs-3">
                        <b class="pull-right"><%= t('.currency')%>  <%= Food.max %></b>
                      </div>  
                    </div>
                    <%= hidden_field_tag :searchQuery, '', id: 'filter_search_field' %>
                    <div class="actions" style="margin-top: 20px;">
                      <%= submit_tag t('.search'), class: 'btn btn-default', style: 'width: 100%;', id: 'filter_search_button'%>
                    </div>
                  <% end %>
                <% else %>
                  <h4 class="text-center" style='padding: 20px;'><%= t('.nodishes')%></h4>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
    </div>
</div>

app/views/restaurants/listing.html.erb
<h3><%= t('.pending')%></h3>

<% if !@restos_pending.empty? %>
	<table class = 'table'>
		<th><%= t('.name')%></th>
		<th><%= t('.description')%></th>
		<th><%= t('.address')%></th>
		<th><%= t('.contact')%></th>
		<th><%= t('.pricerange')%></th>
		<th><%= t('.map')%></th>
	<% @restos_pending.each do |resto| %>
		<tr>
			<td><%= resto.name%></td>
			<td><%= resto.description %></td>
			<td><%= resto.address %></td>
			<td><%= resto.contact%></td>
			<td><%= resto.low_price_range %> - <%= resto.high_price_range %> </td>
			<td><%= resto.map %></td>
			<td><%= link_to 'Edit', edit_restaurant_path(resto.id), method: :get%></td>
			<td><%= link_to 'Accept', restaurant_path(resto.id, restaurant: { status: 'Accepted' }),
				 method: :put%></td>
			<td><%= link_to 'Reject', restaurant_reject_path(resto.id), method: :get%></td>
		</tr>
	<% end%>
	</table>
<% else %>
	<%= t('.nopending')%>
<% end%>

</br><h3> <%= t('.accepted')%></h3>

<% if !@restos_accepted.empty? %>
	<table class = 'table'>
		<th><%= t('.name')%></th>
		<th><%= t('.description')%></th>
		<th><%= t('.address')%></th>
		<th><%= t('.contact')%></th>
		<th><%= t('.pricerange')%></th>
		<th><%= t('.map')%></th>
	<% @restos_accepted.each do |resto| %>
		<tr>
			<td><%= resto.name%></td>
			<td><%= resto.description %></td>
			<td><%= resto.address %></td>
			<td><%= resto.contact%></td>
			<td><%= resto.low_price_range %> - <%= resto.high_price_range %> </td>
			<td><%= resto.map %></td>
			<td><%= link_to 'Edit', edit_restaurant_path(resto.id), method: :get%></td>
		</tr>
	<% end%>
	</table>
<% else %>
	<%= t('.noaccepted')%>
<% end%>


</br><h3><%= t('.rejected')%></h3>


<% if !@restos_rejected.empty? %>
	<table class = 'table'>
		<th><%= t('.name')%></th>
		<th><%= t('.description')%></th>
		<th><%= t('.address')%></th>
		<th><%= t('.contact')%></th>
		<th><%= t('.pricerange')%></th>
		<th><%= t('.map')%></th>
	<% @restos_rejected.each do |resto| %>
		<tr>
			<td><%= resto.name%></td>
			<td><%= resto.description %></td>
			<td><%= resto.address %></td>
			<td><%= resto.contact%></td>
			<td><%= resto.low_price_range %> - <%= resto.high_price_range %> </td>
			<td><%= resto.map %></td>
			<td><%= link_to 'Edit', edit_restaurant_path(resto.id), method: :get%></td>
		</tr>
	<% end%>
	</table>
<% else %>
	<%= t('.norejected')%>
<% end%>

app/views/restaurants/reject.html.erb
<%= t('.rejecttitle', resto: @restaurant.name )%>

<%= form_tag(restaurant_path(@restaurant.id, restaurant: { status: t('.rejectstatus') }), method: :put) do |f| %>
   <div class="form-group">
	  <%= label_tag :message, t('.message') %><br/>
      <%= text_area_tag :message, nil, rows: 10, cols: 20, required: true %>
   </div>
   <div class="actions">
      <%= submit_tag t('.submitletter') %>
   </div>
<% end %>

app/views/restaurants/search.html.erb
<%= render 'restaurants/searchbar'%>

<div class="container" style="margin-top: 50px;">
  <div class="row">
    <div class="col-md-3">
      <div>
        <% if @result.present? && @result.map(&:location).compact.count > 0 %>
          <button type="button" class="btn btn-primary outline" data-toggle="modal" data-target="#mapModal" style="width: 100%; margin-bottom: 10px;">
            <%= t('.viewresult')%> <%= icon('map-marker') %>
          </button>
        <% end %>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading" style="background: #CF2228; color: #fff;">
          <h3 class="panel-title"><%= t('.filters')%></h3>
        </div>
        <div class="panel-body">
          <p><%= t('.sortby')%></p>
          <ul class="list-unstyled filters">
            <li class="<%= filter_active_class(restaurant_search_path(searchQuery: @searchQuery, cuisine: @cuisine, price_range: (@price_range.nil? ? nil : @price_range ), location: @location), @main_active)%>"><%= link_to "Ratings - <small>High to low</small>".html_safe, restaurant_search_path(searchQuery: @searchQuery, cuisine: @cuisine, price_range: (@price_range.nil? ? nil : @price_range ), location: @location) %></li>
            <li class="<%= filter_active_class(restaurant_search_path(searchQuery: @searchQuery, cuisine: @cuisine, sort: 'name', price_range: (@price_range.nil? ? nil : @price_range ), location: @location)) %>"><%= link_to "Name - <small>Alphabetical Order</small>".html_safe, restaurant_search_path(searchQuery: @searchQuery, cuisine: @cuisine, sort: 'name', price_range: (@price_range.nil? ? nil : @price_range ), location: @location) %></li>
            <li class="<%= filter_active_class(restaurant_search_path(searchQuery: @searchQuery, cuisine: @cuisine, location: @location, sort: 'price_low_to_high', price_range: (@price_range.nil? ? nil : @price_range ))) %>"><%= link_to "Price - <small>Low to high</small>".html_safe, restaurant_search_path(searchQuery: @searchQuery, cuisine: @cuisine, location: @location, sort: 'price_low_to_high', price_range: (@price_range.nil? ? nil : @price_range )) %></li>
            <li class="<%= filter_active_class(restaurant_search_path(searchQuery: @searchQuery, cuisine: @cuisine, location: @location, sort: 'price_high_to_low', price_range: (@price_range.nil? ? nil : @price_range ))) %>"><%= link_to "Price - <small>High to low</small>".html_safe, restaurant_search_path(searchQuery: @searchQuery, cuisine: @cuisine, location: @location, sort: 'price_high_to_low', price_range: (@price_range.nil? ? nil : @price_range )) %></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-md-9 search_result">
      
      <% unless @result.blank? %>
        <div style="padding: 0 20px 20px 15px; font-size: 15px; font-weight: bold; color: #CF2228;">
          <%= page_entries_info @result, :entry_name => 'result' %>
        </div>
        
        <div class="list-group restos">
          <% @result.each do |resto| %>
            <div class="col-md-12 col-xs-12 col-lg-12 col-sm-12 hvr-bob">
              <%= link_to resto, class: "list-group-item", style: "margin-bottom: 20px; padding: 0px;" do %>
                <div class="row" style="width: 100%;">
                  <div class="col-lg-4 col-md-5 col-sm-5 col-xs-5">
                    <div class="clearfix" style="background-image: url('<%= asset_path(display_resto(resto))%>'); background-repeat: no-repeat;min-height: 195px; width: 96%; background-position: center; background-size: cover;"></div>
                  </div>
                  <div class="col-lg-8 col-md-7 col-sm-7 col-xs-7" style="padding: 20px;">
                    <div class="" style="">
                      <h4 class="list-group-item-heading">
                        <%= resto.name %>
                      </h4>
                      <p style="font-size: 12px;">
                        <% (resto.ave_ratings.to_i).times do %>
                          <%= icon('star') %>
                        <% end %>
                        <% unless resto.ave_ratings % 1 == 0 %>
                          <%= icon('star-half-o')%>
                          <% (4 - resto.ave_ratings.to_i).times do %>
                            <%= icon('star-o') %>
                          <% end %>
                        <% else %>
                          <% (5 - resto.ave_ratings.to_i).times do %>
                            <%= icon('star-o') %>
                          <% end %>
                        <% end %>
                        &nbsp;&nbsp;(<%= pluralize(resto.ratings.count, 'review') %>)
                      </p>
                      <p class="list-group-item-text" style="margin-top: 20px;">
                        <% if resto.schedules.present?%>
                          <%= icon('info', "<span class='label label-#{(resto.is_open?(DateTime.now) ? 'success' : 'danger')}'> #{(resto.is_open?(DateTime.now) ? t('.open') : t('.close'))}</span>".html_safe, style: 'margin-left: 2px; margin-right: 14px;') %>
                        <% else %>
                          <%= icon('info', "<span class='label label-success'>#{t('.open')}</span>".html_safe, style: 'margin-left: 2px; margin-right: 14px;') %>
                        <% end %>
                      </p>
                      <p class="list-group-item-text ellipsified"  style="margin-top: 10px;"><%= icon('map-marker', resto.address.present? ? resto.address : t('.addressunavailable'), style: 'margin-right: 12px;') %></p>
                      <p class="list-group-item-text" style="margin-top: 10px;"><%= icon('phone', resto.contact, style: 'margin-right: 10px;') %></p>
                      
                    </div>

                  </div>
                </div>
              <% end %>
            </div>
            
          <% end %>
        </div>
      <% else %>
        <h3 class="text-center"><%= t('.noresults')%></h3>
        <%= link_to t('.seerestaurants'), restaurant_search_path(searchQuery: ""), class: 'btn btn-primary center-block', style: 'width: 200px;' %>
      <%= link_to t('.registerrestaurants'), new_restaurant_path, class: 'btn btn-primary outline center-block', style: 'width: 200px; margin-top: 5px;' %>
        <h4 class="text-center"></h4>
      <% end %>
      <div class="pull-right" style="margin-right: 15px;">
        <%= paginate @result %>
      </div>
    </div>
  </div>
</div>

<% if @result.present? %>
  <% @first_resto_with_location = @result.find{|x|!x.location.nil?} %>
  <% if @first_resto_with_location.present? %>
    <script>

      function initMap() {

        var first_result = {lat: <%= @first_resto_with_location.location.latitude %>, lng: <%= @first_resto_with_location.location.longitude %>};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 12,
          center: first_result
        });

        var marker;
        var infowindow = new google.maps.InfoWindow();

        <% @result.each_with_index do |resto, i| %>
          <% if resto.location.present? %>
            marker = new google.maps.Marker({
              position: new google.maps.LatLng(<%= resto.location.latitude %>, <%= resto.location.longitude %>),
              map: map
            });
            google.maps.event.addListener(marker, 'mouseover', (function(marker){
              return function() {
                var content = '<%= link_to(resto.name, resto) %>';
                infowindow.setContent(content);
                infowindow.open(map, marker);
              }
            })(marker));
          <% end %>
        <% end %>
        $('#mapModal').on('shown.bs.modal', function() {
          google.maps.event.trigger(map, "resize");
          map.setCenter(first_result)
        });

      }

    </script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAmeU6jS4Tk8t3OudUKIn7XtciDfe9CbZY&callback=initMap">
    </script>
  <% end %>
<% end %>

<div class="modal fade" id="mapModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div id="map" style="width: 100%; height: 500px; padding: 30px;"></div>
    </div>
  </div>
</div>

app/views/restaurants/show.js.erb
$('#reviews_area').html("<%= escape_javascript render 'ratings/rating' %>");
$('#paginator').html('<%= escape_javascript(paginate(@ratings, :remote => true).to_s) %>');