config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get 'change_locale/:locale' => 'application#change_locale', as: :change_locale
  get 'restaurants/search' => 'restaurants#search', as: :restaurant_search
  get 'restaurants/listing' => 'restaurants#listing', as: :restaurant_listing
  get 'owner/restaurants' => 'users#restaurants', as: :users_restaurant
  get 'owner/restaurants/new' => 'restaurants#owner_new', as: :owner_resto_new
  get 'owner/restaurants/:id' => 'restaurants#owner_edit', as: :owner_resto_edit
  patch 'owner/restaurants/:id' => 'restaurants#owner_patch', as: :owner_resto_patch
  get 'owner/notifications' => 'notifications#index', as: :notifications
  delete 'owner/notifications/:id' => 'notifications#destroy', as: :delete_notification
  get 'restaurants/reject/:id' => 'restaurants#reject', as: :restaurant_reject
  post 'restaurants/ratings/more/:id' => 'ratings#show_more', as: :show_more_rating
  post 'restaurants/ratings/:id' => 'ratings#more_reviews', as: :show_more_reviews
  post 'restaurants/post/more/:id' => 'posts#show_more', as: :show_more_post
  post 'restaurants/pictures/more/:id' => 'pictures#show_more', as: :show_more_picture

  get 'home/about' => 'home#about', as: :about_page
  get 'home/contact' => 'home#contact', as: :contact_page
  get 'home/index'
  get '/cuisines' => 'cuisines#index', as: :cuisines
  devise_for :users, :controllers => { :registrations => :registrations, :omniauth_callbacks => :omniauth_callbacks }
  devise_scope :user do
    delete '/admin/logout', :to => 'active_admin/devise/sessions#destroy', as: :admin_logout
  end
  resources :restaurants, except: :index
  resources :foods
  resources :pictures
  resources :ratings
  resources :schedules
  resources :users, except: :index
  resources :posts
  resources :replies

  post 'likes' => 'likes#create', as: :likes
  delete 'likes' => 'likes#destroy', as: :delete_like

  get 'users/:id' => 'users#show', as: :user_profile

  get '*path' => redirect('/')
  root 'home#index', as: 'home'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :restaurant
  has_many :likes
  has_many :replies
  
  validates :comment, presence: true, allow_blank: false
  
  def user_liked?(user)
    likes.where(user: user).present?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: :show_more
  respond_to :js

  def new
    @post = Post.new
    @post.restaurant = current_user.restaurants.find(params[:resto_id])
    respond_with(@post)
  end

  def create
    @post = Post.new(post_params)
    @post.restaurant = current_user.restaurants.find(params[:resto_id])
    if @post.save
      @posts = @post.restaurant.posts.page params[:page]
      respond_with(@posts)
    else
      @err = "<dl><dt>#{t('.failurestart')}</dt>"
      @post.errors.full_messages.map { |msg| @err << "<dd>#{msg}</dd>" }
      @err << "</dl>"
      respond_with(@posts)
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      @posts = @post.restaurant.posts.page params[:page]
      respond_with(@posts)
    else
      @err = "<dl><dt>#{t('.failurestart')}</dt>"
      @post.errors.full_messages.map { |msg| @err << "<dd>#{msg}</dd>" }
      @err << "</dl>"
      respond_with(@post)
    end
  end

  def destroy
    if @post.destroy
      @posts = @post.restaurant.posts.page params[:page]
      respond_with(@posts)
    end
  end

  def show_more
    @all = params[:more] || nil
    @post_id = params[:post_id]
    @restaurant = Restaurant.find(params[:id])
    respond_with(@all)
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:comment)
  end
end

app/views/posts/_announcement.html.erb
<% if @restaurant.posts.present? %>
  <% @restaurant.posts.order('created_at desc').limit(3).each do |post| %>
    <div class="media" style="padding: 10px; margin: 0px;">
      <div class="media-left">
        <div style="background: url('<%= asset_path(display_resto(post.restaurant)) %>'); background-size: cover; background-position: center center; width: 44px; height: 44px;" class="img-circle"></div>
      </div>
      <div class="media-body" style="max-width: 575px;">
        <h4 class="media-heading">
          <%= post.restaurant.name %> <small> - <%= distance_of_time_in_words_to_now(post.created_at) %> ago</small>
        </h4>
        <p><%= post.comment %></p>
        <% if user_signed_in? %>
          <p>
            <% if post.user_liked?(current_user) %>
              <%= link_to "#{t('.unlike')} #{icon('heart-o', pluralize(post.likes.count, t('.like')))}".html_safe, delete_like_path(user: current_user.id, post: post.id), class: 'btn btn-like-comment', method: :delete, remote: true %> 
            <% else %>
              <%= link_to "#{icon('heart-o', pluralize(post.likes.count, t('.like')))}".html_safe, likes_path(post_id: post.id), class: 'btn btn-like-comment', method: :post, remote: true %> 
            <% end %>
            <%= link_to "#{icon('comments-o', pluralize(post.replies.count, t('.reply')))}".html_safe, new_reply_path(post: post.id), class: 'btn btn-like-comment', remote: true %>
          </p>
        <% else %>
          <p>
            <%= link_to "#{icon('heart-o', pluralize(post.likes.count, 'Like'))}".html_safe, new_user_session_path, class: 'btn btn-like-comment', method: :post, remote: true, disabled: true, data: { toggle: 'tooltip', placement: 'top', title: t('.signintolike') } %> 
            <%= link_to "#{icon('comments-o', pluralize(post.replies.count, 'Reply'))}".html_safe, new_user_session_path, class: 'btn btn-like-comment', remote: true, disabled: true, data: {toggle: 'tooltip', placement: 'top', title: t('.signintoreply') } %>
          </p>
        <% end %>
        
      </div>
    </div>
    <div class="media" style="padding: 0px 50px; margin: 0px;">
      <% if post.replies.count > 3 %>
        <% if @all == "true" && @post_id.to_i == post.id %>
          <%= link_to "#{t('.viewless')} #{icon('caret-up')}".html_safe, show_more_post_path(@restaurant, more: false, post_id: post.id), class: 'center-block text-center', style: 'width: 100%; background-color: whitesmoke; padding: 3px; color: #777777;', remote: true, method: :post %>
        <% else %>
          <%= link_to "#{t('.viewall')} (#{post.replies.count - 3}) #{icon('caret-down')}".html_safe, show_more_post_path(@restaurant, more: true, post_id: post.id), class: 'center-block text-center', style: 'width: 100%; background-color: whitesmoke; padding: 3px; color: #777777;', remote: true, method: :post %>
        <% end %>
      <% end %>
    </div>
    <% if post.replies.present? %>
      <% (@all == "true" && @post_id.to_i == post.id ? post.replies : post.replies.last(3)).each do |reply| %>
        <div class="media" style="padding: 10px 50px 10px 63px; margin: 0px;">
          <div class="media-left">
            <div style="background: url('<%= asset_path(display_user(reply.user)) %>'); background-size: cover; background-position: center center; width: 40px; height: 40px;" class="img-circle"></div>
          </div>
          <div class="media-body" style="max-width: 565px;">
            <h5 class="media-heading">
              <%= reply.user.name %> <small> - <%= distance_of_time_in_words_to_now(reply.created_at) %> ago</small>
              <% if reply.user === current_user %>
                <span style="margin-left: 20px;">
                  <%= link_to "#{icon('trash')}".html_safe, reply_path(reply, post: true), method: :delete, remote: true %>
                </span>
              <% end %>
            </h5>
            <p><%= reply.comment %></p>
          </div>
        </div>
      <% end %>
    <% end %>
    
    <div id="post_reply_<%= post.id %>" style="padding: 5px 20px;">
          
    </div>
  <% end %>
<% end %>

app/views/posts/_edit.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <h4 class="modal-title" id="myModalLabel"><%= t('.editpost')%></h4>
</div>
<div class="modal-body">
  <div id = 'post_error_area'></div>
  <%= form_for(@post, url: post_path(@post.id), method: :put, remote: true) do |f| %>
    
    <div class="form-group">
      <%= f.label t('.message') %>
      <%= f.text_area :comment, class: 'form-control', required: true %>
    </div>
    
    <div class="actions">
      <%= f.submit t('.editpost'), class: 'btn btn-primary', style: 'width: 100%;' %>
    </div>
  
  <% end %>
</div>

app/views/posts/_new.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <h4 class="modal-title" id="myModalLabel"><%= t('.addpost')%></h4>
</div>
<div class="modal-body">
  <div id = "post_alert_area"></div>
  <%= form_for(@post, url: posts_path(resto_id: @post.restaurant), remote: true) do |f| %>
    <div class="form-group">
      <%= f.text_area :comment, class: 'form-control', placeholder: t('.placepost'), required: true %>
    </div>
    <div class="actions">
      <%= f.submit t('.createpost'), class: 'btn btn-primary', style: 'width: 100%;' %>
    </div>
  
  <% end %>
</div>

app/views/posts/_post.html.erb
<% unless @posts.empty? %>
    <div class="table-responsive">
      <table class="table table-bordered">
        <thead>
          <tr style="background-color: #404040;">
            <th><%= t('.announcementpost')%></th>
            <th><%= t('.dateposted')%></th>
            <th><%= t('.actions')%></th>
          </tr>
        </thead>
        <tbody>
          <% @posts.each do |post| %>
            <tr>
              <td><%= post.comment %></td>
              <td><%= post.created_at.strftime("%B %d, %Y - %I:%M %p")%></td>
              <td style="width: 150px;"><%= link_to t('.edit'), edit_post_path(post.id), class: 'btn btn-primary outline', remote: true,  data: { toggle: 'modal', target: '#myModal'} %> <%= link_to t('.delete'), post_path(post.id), class: 'btn btn-danger', method: :delete, data: { confirm: t('.confirm') }, remote: true%></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
<% else %>
  <%= t('.noposts')%>
  <% end %>

app/views/posts/create.js.erb
<% unless @post.errors.any? %>
  $('#myModal').modal("hide")
  $('#post_area').html("<%= j render('posts/post', post: @post) %>")
<% else %>
  $('#post_alert_area').html("<div class='alert alert-danger'><%= @err.html_safe %></div>")
  $('#post_alert_area').parent().addClass('has-error')
<% end %>  

app/views/posts/destroy.js.erb
$('#post_area').html("<%= j render(@post) %>")

app/views/posts/edit.js.erb
$("#show-modal").html('<%= j render "edit" %>')

app/views/posts/new.js.erb
$("#show-modal").html('<%= j render "new" %>')

app/views/posts/show_more.js.erb
$('#announcement_area').html("<%= j render('posts/announcement', all: @all, restaurant: @restaurant)%>")

app/views/posts/update.js.erb
<% unless @post.errors.any? %>
  $('#myModal').modal("hide")
  $('#post_area').html("<%= j render(@post) %>")
<% else %>
    $("#post_error_area").html("<%= @err.html_safe %>")
    $("#post_error_area").addClass("alert alert-danger")
<% end %>  